
export const DRAG_OVER_EVENT = "DRAG_OVER_EVENT";
export const CANVAS_SCROLL = "CANVAS_SCROLL";
export const REFRESH_NODE = "REFRESH_NODE";
export const SELECT_NODE = "SELECT_NODE";
export const REFRESH_SELECT_STATE = "REFRESH_SELECT_STATE";