export default{
  name:'OneToManyTable',
  props: {
    elevation: 6,
    title:'规格库存',
    collapsible: true,
    marginTop:2,
    open:true,
    size:"small",
    field:'specs',
    columns:[
      {
        field:'image',
        label:'图片',
        input:{
          name:'MediaSelect',
          props:{
            width:'60px',
          }
        }
      },
      {
        field:'name',
        label:'名称',
        props:{
          width:'200px',
        },

        input:{
          name:'TextBox',
          props:{
            variant:'outlined',
            size:'small',
          }
        }
      },
      {
        field:'color',
        label:'颜色',
        input:{
          name:'TextBox',
          props:{
            variant:'outlined',
            size:'small',
          }
        }
      },
      {
        field:'category',
        label:'型号',
        input:{
          name:'SelectBox',
          props:{
            variant:"outlined",
            size:'small',
            withoutEmpertyItem:false,                        
            items:[
              {
                slug:'100',
                label:'100'
              },
              {
                slug:'200',
                label:'200'
              },
              {
                slug:'300',
                label:'300'
              }
            ]
          }
        },
      },
      {
        field:'stock',
        label:'库存',
        input:{
          name:'TextBox',
          props:{
            variant:'outlined',
            size:'small',
          }
        }
      },


    ]         
  },            
}
